### PR TITLE
Add technical acceptance to feature request tmpl

### PR DESCRIPTION
**Pull request by countnoobula**
## Proposed changes

_Description of the changes implemented by this PR, feel free to be as verbose as needed_

This adds a new segment to the feature request template that allows the
engineering manager or lead developer to layout a set of criteria to
assist in providing direction for the implementation.

This will hopefully mirror the Acceptance Criteria field from the Client
segment, and allow things to be structured and communicated better in
the issues.

## Types of changes

What type of changes does your code introduce?
_Put an `x` in the boxes that apply, leave blank if none_

- [ ] Frontend
- [ ] Backend
- [ ] Bugfix
- [ ] New feature
- [ ] Component of Major Release
- [ ] Project Management
- [x] Quality of Life
- [ ] Test Improvements

## Checklist

_Put an `x` in the boxes that apply._

- [ ] Local Cypress Tests Pass with my changes (`yarn cypress:run`)
- [ ] Lint and unit tests pass locally with my changes (`yarn lint && ./vendor/bin/phpunit`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Dependant PRs

_List Pull Requests below in format `#<ISSUE-NUMBER>`_
- ...

## Relevant Issues

_List Issues below in format `#<ISSUE-NUMBER> [Full|Partial]`_
- ...

## Description

_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc._

### CODE REVIEW

**Review by willemwe0 — CHANGES_REQUESTED** [review]
I feel this is too much micromanagement. 

We have the technical description (before the issue work starts) as a way to enhance the estimation, forcing you to consider more technical issues that can arise. 

Now we are forcing a specific implementation (which often changes) and more documentation to keep up to date if it changes.

**Review by robguy21 — APPROVED** [review]

**Comment by sscholle** [comment]
@willemwe0 agreed, that section will most likely never be updated properly and be left as last (after dev is complete) i'm not sure our planning process is that thorough

**Comment by robguy21** [comment]
@sscholle @willemwe0 then we need to be willing to, if need be, add to the acceptance criteria after the fact.

If a technical acceptance criteria exists it needs to be recorded in the issue, not left in the void of verbal communication.

**Comment by sscholle** [comment]
@countnoobula this seems to be largely resolved, see the Luxity Feature Request templates, can we close this?

**Pull request closed without merging**
